<ul class="toc">
    <li><span>Introduction</span> <a href="#">Page 1</a>
        <ol>
            <li><span>Subtitle 1</span> <a href="#">Page 1</a></li>
            <li><span>Subtitle 2</span> <a href="#">Page 1</a></li>
        </ol>
    </li>
    <li><span>Experiment</span> <a href="#">Page 2</a></li>
    <li><span>Conclusion</span> <a href="#">Page 4</a></li>
    <li><span>Discussion</span> <a href="#">Page 5</a></li>
</ul>
